version: '2'
services:
 redis:
  build: ./redis
  ports: 
   - "6379:6379"
 postgres:
  build: ./postgres
  ports: 
   - "5432:5432"
 rabbitmq:
  build: ./rabbitmq
  ports: 
   - "5672:5672"
   - "15671:15672"
 nginx:
  build: ./nginx
  ports: 
   - "80:80"
