version: '3'
services:
  landapi:
    build: "./landapi"
 #   ports:
  #      - "8000:8000"
    networks:
      default:
        ipv4_address: 192.168.1.52
networks:
  default:
    external:
      name: MyBridge
